# Site settings
title: BitcoinCasinoDeutsch.de
description: > # this means to ignore newlines until "baseurl:"
  Testberichte, Meinungen und Erfahrungen rund um deutschsprachige Casinos, die Bitcoin akzeptieren
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bitcoincasinodeutsch.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: cayman
